neyu:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 127.0.0.1
      user: tms_admin
      password: Usfy3siOO%fX
      port: 5555
      dbname: tms_central_tmp # or database instead of dbname
      schema: superset
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      retries: 1  # default 1 retry on error/timeout when opening connections